# Site settings
title: Aditya Yogish Pai 
name: Aditya Yogish Pai

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://mlhackerblog.wordpress.com/
 - title: GitHub
   url: https://github.com/AdityaPai2398
 - title: LinkedIn
   url: https://www.linkedin.com/in/aditya-yogish-pai-2ab414132/ 

#Any buzzword skills you want to include
skills:
 - Machine Learning
 - Deep Learning
 - Java
 - C++
 - Python
 - C
 - SQL
 - Computer Vision
 - HTML CSS 
 - PHP

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://mlhackerblog.wordpress.com/?feed=rss

#Work experience is required
roles:
 - title: Blogger
   start: September 2017
   end: Ongoing
   employer: Self Employed
   description: Writing blogs on various trends and projects in Machine Learning,Deep Learning,BlockCHain and Algorithms
 - title: Research Student
   start: May 2017
   end: August 2017
   employer: NMAMIT Nitte
   description: Worked on detection of vehicles and pedestrians using Haar Cascade with background subtraction.Develoment was mainly done using OpenCV and Python,
 - title: Web Developer
   start: April 2017
   end: May 2017
   employer: MotivateBox
   description: Added features such as Social Login buttons,Social Widgets.<br>Fixed various design issues.<br>All work was done on shopify platform using Liquid Language.


#Education is required
education:
 - level: Bachelor Of Engineering
   date: 2005-19
   subject: Information Science and Engineering
   school: NMAM Institute of Technology

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/2dabea88a0ccaacb80ba21950f99394e
   courses:
    - title: Neural Networks and Deep Learning
      link:  https://www.coursera.org/learn/neural-networks-deep-learning
      #optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: March , 2018
    - title: Machine Learning for Data Analysis
      link: https://www.coursera.org/learn/machine-learning-data-analysis
      #optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: December,2017
    - title: Machine Learning
      link: https://www.coursera.org/learn/machine-learning
      #optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: November,2017
    - title: Google Cloud Platform Fundamentals: Core Infrastructure
      link: https://www.coursera.org/learn/gcp-fundamentals/lecture/I6zpd/welcome-to-gcp-fundamentals
      #optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: November,2017
     

#List of interesting Github repo/projects to include - optional
github:
 - robhinds/learning-neural-networks
 - robhinds/akka-http-rest-api-sample
 - robhinds/twitter-sentiment-analysis
 - robhinds/spring-reactor-twitter
 - robhinds/microservices
 - robhinds/spring-social-geeklist
 - robhinds/spring-social-stackoverflow
 - robhinds/food2vec
 - robhinds/SpringMongoIntegrationExample
 - robhinds/SpringNeo4JWebApp
 - robhinds/AndroidChuckQuiz
 - robhinds/AndroidRssReader





#An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |
#   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>). <br/><br/>
#   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework (although current role uses ColdFusion for server side web stack). I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
#   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
#   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
#   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
#   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)

theme: jekyll-theme-cayman
